services:
  app:
    image: tachybase/tachybase-all:latest
    environment:
      - APP_KEY=your-secret-key # you should change here
      - DB_DIALECT=postgres
      - DB_HOST=db
      - DB_DATABASE=tachybase
      - DB_USER=tachybase
      - DB_PASSWORD=tachybase
    volumes:
      - ./storage:/app/storage
    ports:
      - "3000:3000"
    depends_on:
      - db
    init: true
  db:
    image: postgres:16
    restart: always
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_USER: tachybase
      POSTGRES_DB: tachybase
      POSTGRES_PASSWORD: tachybase
    volumes:
      - ./storage/db/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "3080:80"
    volumes:
      - ./storage/db/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tachybase.com
      PGADMIN_DEFAULT_PASSWORD: admin@tachybase.com
    depends_on:
      - db
