import { CollectionOptions } from '@tachybase/client';

export const collection: CollectionOptions = {
  key: 'ojwl16z833h',
  name: 'cloudComponents',
  title: '云组件',
  hidden: false,
  description: null,
  fields: [
    {
      key: '7ual55t73vc',
      name: 'id',
      type: 'bigInt',
      interface: 'integer',
      description: null,
      collectionName: 'cloudComponents',
      parentKey: null,
      reverseKey: null,
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      uiSchema: {
        type: 'number',
        title: '{{t("ID")}}',
        'x-component': 'InputNumber',
        'x-read-pretty': true,
      },
    },
    {
      key: 'j9r9grvl0v0',
      name: 'createdAt',
      type: 'date',
      interface: 'createdAt',
      description: null,
      collectionName: 'cloudComponents',
      parentKey: null,
      reverseKey: null,
      field: 'createdAt',
      uiSchema: {
        type: 'datetime',
        title: '{{t("Created at")}}',
        'x-component': 'DatePicker',
        'x-component-props': {},
        'x-read-pretty': true,
      },
    },
    {
      key: 'ng4sopamz8s',
      name: 'createdBy',
      type: 'belongsTo',
      interface: 'createdBy',
      description: null,
      collectionName: 'cloudComponents',
      parentKey: null,
      reverseKey: null,
      target: 'users',
      foreignKey: 'createdById',
      uiSchema: {
        type: 'object',
        title: '{{t("Created by")}}',
        'x-component': 'AssociationField',
        'x-component-props': {
          fieldNames: {
            value: 'id',
            label: 'nickname',
          },
        },
        'x-read-pretty': true,
      },
      targetKey: 'id',
    },
    {
      key: 'bgz2nz990hs',
      name: 'updatedAt',
      type: 'date',
      interface: 'updatedAt',
      description: null,
      collectionName: 'cloudComponents',
      parentKey: null,
      reverseKey: null,
      field: 'updatedAt',
      uiSchema: {
        type: 'string',
        title: '{{t("Last updated at")}}',
        'x-component': 'DatePicker',
        'x-component-props': {},
        'x-read-pretty': true,
      },
    },
    {
      key: 'd4buc2p023i',
      name: 'updatedBy',
      type: 'belongsTo',
      interface: 'updatedBy',
      description: null,
      collectionName: 'cloudComponents',
      parentKey: null,
      reverseKey: null,
      target: 'users',
      foreignKey: 'updatedById',
      uiSchema: {
        type: 'object',
        title: '{{t("Last updated by")}}',
        'x-component': 'AssociationField',
        'x-component-props': {
          fieldNames: {
            value: 'id',
            label: 'nickname',
          },
        },
        'x-read-pretty': true,
      },
      targetKey: 'id',
    },
    {
      key: 'mugo60v2vkn',
      name: 'name',
      type: 'string',
      interface: 'input',
      description: null,
      collectionName: 'cloudComponents',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        title: '组件名称',
      },
      unique: true,
      primaryKey: false,
    },
    {
      key: 'f1chvlpvplp',
      name: 'code',
      type: 'text',
      interface: 'textarea',
      description: null,
      collectionName: 'cloudComponents',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        type: 'string',
        'x-component': 'Input.TextArea',
        title: '组件代码',
      },
    },
    {
      key: '0ruhfmjlwzv',
      name: 'data',
      type: 'json',
      interface: 'json',
      description: '组件测试数据，可以用来 mock 组件的数据',
      collectionName: 'cloudComponents',
      parentKey: null,
      reverseKey: null,
      defaultValue: null,
      uiSchema: {
        type: 'object',
        'x-component': 'Input.JSON',
        'x-component-props': {
          autoSize: {
            minRows: 5,
          },
        },
        default: null,
        title: '组件数据',
      },
      jsonb: false,
    },
    {
      key: 'ni0obrsc3g0',
      name: 'description',
      type: 'text',
      interface: 'textarea',
      description: null,
      collectionName: 'cloudComponents',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        type: 'string',
        'x-component': 'Input.TextArea',
        title: '组件文档',
      },
    },
    {
      key: 'biyfqb10he6',
      name: 'enabled',
      type: 'boolean',
      interface: 'checkbox',
      description: null,
      collectionName: 'cloudComponents',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        'x-component-props': {
          showUnchecked: true,
        },
        type: 'boolean',
        'x-component': 'Checkbox',
        title: '是否启用',
      },
    },
  ],
  logging: true,
  autoGenId: true,
  createdAt: true,
  createdBy: true,
  updatedAt: true,
  updatedBy: true,
  template: 'general',
  view: false,
  schema: 'public',
  titleField: 'name',
  filterTargetKey: 'id',
};
