name: PR Workflow
on:
  pull_request:
    branches:
      - dev

permissions:
  contents: write

jobs:
  CI:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: config registry
        run: npm config set registry https://npm.daoyoucloud.com/
      - name: install pnpm
        uses: pnpm/action-setup@v3
        with:
          standalone: true
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV          
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: pnpm-store
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build:p
