name: PR Workflow
on:
  pull_request:
    branches:
      - dev

permissions:
  contents: write

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: ${{ vars.REGISTRY_URL }}
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install
      - name: Build
        run: pnpm build:p
