name: PR Workflow
on:
  pull_request:
    branches:
      - dev

permissions:
  contents: write

env:
  npm_config_registry: ${{ vars.REGISTRY_URL }}

jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
          registry-url: ${{ vars.REGISTRY_URL }}
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install
      - name: Build
        run: pnpm build:p
