name: Release Workflow
on:
  push:
    branches:
      - 'release-*'

permissions:
  contents: write

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: ${{ vars.REGISTRY_URL }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build:p
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMTOKEN }}
        run: pnpm -r publish --access=public --no-git-checks --publish-branch ${{ gitea.ref }}
