name: Release Workflow
on:
  push:
    branches:
      - 'release-*'

permissions:
  contents: write

env:
  npm_config_registry: ${{ vars.REGISTRY_URL }}

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
          registry-url: ${{ vars.REGISTRY_URL }}
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install
      - name: Build
        run: pnpm build:p
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMTOKEN }}
          SENTRY_DSN: ${{ vars.SENTRY_DSN }}
          SENTRY_TRACE_ENABLE: ${{ vars.SENTRY_TRACE_ENABLE }}
          SENTRY_TRACE_SAMPLE_RATE: ${{ vars.SENTRY_TRACE_SAMPLE_RATE }}
          SENTRY_TRACE_PROPAGATION_TARGETS: ${{ vars.SENTRY_TRACE_PROPAGATION_TARGETS }}
          SENTRY_SESSION_REPLAY_ENABLE: ${{ vars.SENTRY_SESSION_REPLAY_ENABLE }}
          SENTRY_SESSION_REPLAY_SAMPLE_RATE: ${{ vars.SENTRY_SESSION_REPLAY_SAMPLE_RATE }}
          SENTRY_SESSION_REPLAY_ONERROR_SAMPLE_RATE: ${{ vars.SENTRY_SESSION_REPLAY_ONERROR_SAMPLE_RATE }}
        run: pnpm -r publish --access=public --no-git-checks --publish-branch ${{ gitea.ref }}
