// @ts-ignore
import { version } from '../../package.json';

const deps: Record<string, string> = {
  '@tachybase': `${version.split('.').slice(0, 2).join('.')}.x`, // 0.12.x

  jsonwebtoken: '8.x',
  'cache-manager': '5.x',
  sequelize: '6.x',
  umzug: '3.x',
  'async-mutex': '0.3.x',
  '@formulajs/formulajs': '4.x',
  mathjs: '10.x',
  winston: '3.x',
  'winston-daily-rotate-file': '4.x',
  koa: '2.x',
  '@koa/cors': '3.x',
  multer: '2.x',
  '@koa/multer': '3.x',
  'koa-bodyparser': '4.x',
  react: '18.x',
  'react-dom': '18.x',
  'react-router': '6.x',
  'react-router-dom': '6.x',
  antd: '5.x',
  'antd-style': '3.x',
  '@ant-design/icons': '5.x',
  '@ant-design/cssinjs': '1.x',
  i18next: '23.x',
  'react-i18next': '15.x',
  '@dnd-kit/accessibility': '3.x',
  '@dnd-kit/core': '6.x',
  '@dnd-kit/modifiers': '7.x',
  '@dnd-kit/sortable': '8.x',
  '@dnd-kit/utilities': '3.x',
  dayjs: '1.x',
  mysql2: '3.x',
  pg: '8.x',
  'pg-hstore': '2.x',
  sqlite3: '5.x',
  supertest: '6.x',
  axios: '1.x',
  '@emotion/css': '11.x',
  ahooks: '3.x',
  lodash: '4.x',
  'china-division': '2.x',
  cronstrue: '2.x',
};

export default deps;
