name: build tachybase all

on:
  push:
    tags:
      - 'all-release-*'

env:
  npm_config_registry: ${{ vars.REGISTRY_URL }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: registry."docker.io".mirrors=["docker.1panel.live"]
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKERHUB_URL }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Extract and format tag name
        id: extract_tag
        run: echo version=`echo "${{ github.ref }}" | cut -d'/' -f3` >> "$GITHUB_OUTPUT"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/tachybase-all/Dockerfile
          push: true
          build-args: |
            TACHYBASE_VERSION=${{ steps.extract_tag.outputs.version }}
            NPM_REGISTRY=${{ vars.REGISTRY_URL }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ vars.DOCKERHUB_URL }}/tachybase/tachybase-all:${{ steps.extract_tag.outputs.version }}
            ${{ vars.DOCKERHUB_URL }}/tachybase/tachybase-all:latest
