name: Manual Build Tachybase test

on:
  workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Build with pkg
        run: pnpm --filter '@tachybase/engine' run build

      - name: Check build output
        run: ls -lh apps/engine/dist

      - name: Rename files for release
        run: |
          mv apps/engine/dist/engine-linux apps/engine/dist/engine-linux-x64
          mv apps/engine/dist/engine-macos apps/engine/dist/engine-macos-x64
          mv apps/engine/dist/engine-win apps/engine/dist/engine-win-x64

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            apps/engine/dist/engine-linux-x64
            apps/engine/dist/engine-macos-x64
            apps/engine/dist/engine-win-x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
