name: Manual Build Tachybase All

on:
  workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Tag Name
        id: extract_tag
        run: echo version=`echo "${{ github.ref }}" | cut -d'/' -f3` >> "$GITHUB_OUTPUT"

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/tachybase-all/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            TACHYBASE_VERSION=${{ steps.extract_tag.outputs.version }}
          tags: |
            tachybase/tachybase-all:${{ steps.extract_tag.outputs.version }}
            tachybase/tachybase-all:latest
