name: manual build tachybase

on:
  workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Echo Tag Name
        run: echo "${{ github.ref }}"
      - name: Extract Tag Name
        id: extract_tag
        run: echo version=`echo "${{ github.ref }}" | cut -d'/' -f3` >> "$GITHUB_OUTPUT"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/tachybase/Dockerfile
          push: true
          build-args: |
            TACHYBASE_VERSION=${{ steps.extract_tag.outputs.version }}
          tags: |
            tachybase/tachybase:${{ steps.extract_tag.outputs.version }}
            tachybase/tachybase:latest
