name: Tachybase Base Image With Postgres

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'The Docker tag to publish (e.g., "1.0.0", "latest")'
        required: true
        default: 'latest'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/tego-node-pg/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            tegojs/tego-node-pg:${{ github.event.inputs.docker_tag }}
            tegojs/tego-node-pg:latest
